---
- name: create vpc
  ec2_vpc_net:
    name: "{{ aws_network_name }}-vpc"
    state: present
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ region }}"

- name: get vpc id
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ aws_network_name }}-vpc"
  register: vpc_facts

- name: vpc id
  debug: 
    var: vpc_facts['vpcs'][0]['id']

- name: create private subnet 1
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"
    cidr: "{{ private_subnet_1_cidr }}"
    region: "{{ region }}"
    az: "{{ region }}b"
    resource_tags:
      Name: "{{ aws_network_name }}-private-1"
  register: private_subnet_1

- name: mysql private subnet id 1
  debug: 
    var: private_subnet_1['subnet']['id']

- name: create private subnet 2
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"
    cidr: "{{ private_subnet_2_cidr }}"
    region: "{{ region }}"
    az: "{{ region }}c"
    resource_tags:
      Name: "{{ aws_network_name }}-private-2"
  register: private_subnet_2

- name: mysql private subnet id 2
  debug:
    var: private_subnet_2['subnet']['id']

- name: create public subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"
    cidr: "{{ public_subnet_cidr }}"
    region: "{{ region }}"
    az: "{{ region }}a"
    resource_tags:
      Name: "{{ aws_network_name }}-public"
  register: public_subnet

- name: public subnet id
  debug: 
    var: public_subnet['subnet']['id']

- name: create internet gateway    
  ec2_vpc_igw:
    vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"
    state: present
    region: "{{ region }}"
  register: igw

- name: get internet gateway id
  debug: 
    var: igw['gateway_id']

- name: set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "{{ aws_network_name }}-public"
    subnets:
      - "{{ private_subnet_1['subnet']['id'] }}"
      - "{{ private_subnet_2['subnet']['id'] }}"
      - "{{ public_subnet['subnet']['id'] }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw['gateway_id'] }}"
  register: public_route_table
