---

- name: Update uwsgi systemd service file
  copy:
    src: uwsgi.service
    dest: "{{ flaskapp_service_directory }}/uwsgi.service"
    owner: root
    group: root
    mode: '644'

- name: Create uwsgi ini configuration file for the application
  template: 
    src: app_uwsgi_ini.j2 
    dest: "{{ flaskapp_uwsgi_directory }}/{{ flaskapp_app_name }}.ini"
    owner: uwsgi
    group: uwsgi
    mode: '644'
  notify: restart uwsgi
