region: eu-west-1
zone: eu-west-1a
keypair: ssh_access_key
security_group: nodejs_sec_gr
instance_type: t2.micro
volumes:
  - device_name: /dev/sda1
    volume_type: gp2
    volume_size: 20
    delete_on_termination: true
# Git private key for app deployment
deployment_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          <vault_hash_here>
startindex: "1"
